/* Español como lengua extranjera. Contenido original; referencia curricular: PCIC.
   Cada fila: título | explicación | ejemplo | ejercicio | solución | error | corrección. */
const spanishLevels = ['A1','A2','B1','B2','C1','C2'];
const spanishLevel = pupil => spanishLevels.includes(pupil?.spanishLevel) ? pupil.spanishLevel : spanishLevels.includes(pupil?.course) ? pupil.course : 'A1';
const studentSubjectCourse = (pupil, subject) => subject === 'Español' ? spanishLevel(pupil) : pupil?.course || '';
const spanishLevelField = value => '<div class="spanish-level-field"><label for="spanishLevel">Nivel de español</label><select id="spanishLevel" name="spanishLevel">'+spanishLevels.map(level=>'<option'+(level===(value||'A1')?' selected':'')+'>'+level+'</option>').join('')+'</select><small>Independiente del curso escolar; A1 es el nivel inicial.</small></div>';
const spanishLearningGuidance = {
 A1:'Comunicación inicial: frases sencillas, vocabulario cotidiano, apoyos y modelos breves.',
 A2:'Intercambios cotidianos: descripciones, planes y relatos breves con conectores sencillos.',
 B1:'Comunicación autónoma: narrar experiencias, explicar razones y resolver situaciones habituales.',
 B2:'Argumentación y precisión: opiniones matizadas, textos claros y registros adecuados.',
 C1:'Comunicación avanzada: inferencias, cohesión, matices y uso flexible del registro.',
 C2:'Dominio flexible: reformulación precisa, implicaturas y diferencias sutiles de significado.'
};
function temarioLanguageTable(topic){
 const table=topic.languageTable;
 if(!table)return '';
 return '<h4>Formas de referencia</h4><table><thead><tr>'+table.head.map(cell=>'<th>'+esc(cell)+'</th>').join('')+'</tr></thead><tbody>'+table.rows.map(row=>'<tr>'+row.map(cell=>'<td>'+esc(cell)+'</td>').join('')+'</tr>').join('')+'</tbody></table>';
}
(() => {
 const units = {
 A1: `Saludos y presentaciones|Para saludar usamos «hola» o un saludo según el momento: «buenos días», «buenas tardes». Para presentarnos, «me llamo» indica el nombre y «soy» puede indicar nacionalidad o profesión. «¿Cómo te llamas?» se dirige a una persona con trato informal.|—Hola, me llamo Ana. ¿Cómo te llamas? —Me llamo Luis. Encantado.|Completa: Me ___ Ana.|llamo|Yo llamo Ana.|Me llamo Ana.
Pronunciación, letras y sílabas|Las cinco vocales españolas mantienen una pronunciación relativamente estable. La h no representa un sonido; la ñ es distinta de n. Para deletrear un nombre decimos los nombres de sus letras. La tilde marca la sílaba tónica cuando lo exigen las reglas de acentuación.|«Año» y «ano» son palabras distintas. «Casa» tiene dos sílabas: ca-sa. «Hola» empieza con h muda.|Completa «año» con la letra que falta: a___o.|ñ|La h de hola se pronuncia como una j.|La h de hola no se pronuncia.
Números, edad y datos personales|La edad se expresa con «tener», no con «ser». Los números sirven para dar teléfonos, cantidades y precios. Para preguntar usamos «¿Cuántos años tienes?» o «¿Cuál es tu número?». En teléfonos podemos leer las cifras por separado para facilitar la comprensión.|—¿Cuántos años tienes? —Tengo veintidós años. Mi número empieza por seis, dos, tres.|Completa: ___ veintidós años.|Tengo|Soy veintidós años.|Tengo veintidós años.
Género, número y artículos|Los artículos concuerdan con el sustantivo: el libro, la mesa, los libros, las mesas. Muchos nombres terminados en -o son masculinos y muchos en -a femeninos, pero hay excepciones, como «el día». El plural suele añadir -s tras vocal y -es tras consonante.|Un libro → dos libros. Una ciudad → dos ciudades. «La mano» es femenino aunque termina en -o.|Completa: dos ciudad___.|es|Los mesa son grandes.|Las mesas son grandes.
Ser, estar y hay|«Ser» identifica o caracteriza; «estar» expresa localización de personas u objetos y estados; «hay» presenta la existencia de algo. Al presentar un lugar usamos «hay»; cuando identificamos uno concreto podemos decir dónde «está». No son equivalentes.|Hay una farmacia en esta calle. La farmacia está junto al banco. Es pequeña.|Completa: En mi barrio ___ una farmacia.|hay|Hay la farmacia junto al banco.|La farmacia está junto al banco.
Presente y rutinas|Los verbos regulares cambian su terminación según la persona: hablar → hablo, hablas, habla; comer → como, comes, come; vivir → vivo, vives, vive. El presente permite hablar de hábitos. El pronombre sujeto puede omitirse si la terminación identifica a la persona.|Trabajo por la mañana y vivo cerca del centro. Ana trabaja por la tarde.|Completa con vivir: Ana ___ en Madrid.|vive|Ana vivir en Madrid.|Ana vive en Madrid.
Preguntas e información práctica|Qué pide información general; dónde pregunta por un lugar; cuándo por un momento; cómo por la manera. Una pregunta directa lleva signos de apertura y cierre, y los interrogativos llevan tilde. La entonación ayuda a distinguir una pregunta de una afirmación.|—¿Dónde está la estación? —En la plaza. —¿Cuándo abre? —A las ocho.|Completa: ¿___ está la estación? —En la plaza.|Dónde|Donde está la estación?|¿Dónde está la estación?
Familia, posesión y descripción|Mi, tu y su acompañan al sustantivo; en plural usamos mis, tus y sus. El posesivo concuerda con lo poseído, no con quien posee. Para describir personas empleamos «ser» con características y «tener» para edad o determinados rasgos físicos.|Mi hermana es alta y tiene el pelo oscuro. Mis hermanos viven aquí.|Completa: ___ hermanos viven aquí (posesión de yo).|Mis|Mi hermanos viven aquí.|Mis hermanos viven aquí.
Gustos y preferencias|En «me gusta el café», lo que produce el gusto es el sujeto. Usamos «gusta» con un nombre singular o infinitivo y «gustan» con nombres plurales. A mí, a ti o a Ana aclaran quién siente el gusto; no sustituyen siempre al pronombre me, te o le.|Me gusta cocinar. Me gustan las frutas. A Ana le gusta el té.|Completa: Me ___ las frutas.|gustan|Me gusta las frutas.|Me gustan las frutas.
Horas, fechas y horarios|Para la una usamos «es la una»; para las demás horas, «son las…». Para indicar el momento de una actividad decimos «a la una» o «a las dos». Las fechas suelen seguir día, mes y año. Los días de la semana se escriben con minúscula.|Son las dos. La clase empieza a las tres. Hoy es lunes, cinco de mayo.|Completa: La clase empieza ___ las tres.|a|La clase empieza en las tres.|La clase empieza a las tres.
Comprar y pedir en una cafetería|Para pedir podemos decir «un café, por favor» o «quiero un café». «¿Cuánto cuesta?» pregunta por un precio singular; «¿cuánto cuestan?» por varios objetos. Un saludo, por favor y gracias hacen el intercambio más adecuado. Distinguimos querer de tener.|—Buenos días. Un café, por favor. —Son dos euros. —Gracias.|Completa: ¿Cuánto ___ este libro?|cuesta|¿Cuánto cuestan este libro?|¿Cuánto cuesta este libro?
Direcciones y desplazamientos|Para localizar usamos delante de, detrás de, cerca de o al lado de. «Ir a» indica destino; «venir» depende del lugar del hablante. A más el se contrae en al; de más el, en del. Para orientar podemos usar «sigue recto» o «gira a la derecha».|Voy al mercado. La estación está cerca del parque. Sigue recto hasta la plaza.|Completa: Voy ___ mercado.|al|Voy a el mercado.|Voy al mercado.`,
 A2: `Pasado: experiencias recientes|El pretérito perfecto se forma con haber en presente y un participio: he hablado, has comido, ha vivido. Relaciona el hecho con un marco que el hablante considera vigente. Su frecuencia cambia entre regiones; no todas usan igual «hoy he ido» y «hoy fui».|Esta semana he visitado a mi hermana. He comido con ella dos veces.|Completa: Esta semana ___ visitado a mi hermana (yo).|he|Yo ha visitado a mi hermana.|Yo he visitado a mi hermana.
Pasado: hechos terminados|El pretérito indefinido presenta hechos delimitados en el pasado. En verbos regulares: hablé, hablaste, habló; comí, comiste, comió. Marcadores como ayer o el año pasado ayudan a situar el relato. Verbos frecuentes como ir y ser tienen formas irregulares.|Ayer fui al centro, compré pan y volví a casa. El año pasado viajé a Perú.|Completa con comprar: Ayer ___ pan (yo).|compré|Ayer yo compró pan.|Ayer yo compré pan.
Describir hábitos y situaciones pasadas|El imperfecto presenta hábitos, descripciones o situaciones en desarrollo sin delimitar su final. Hablar da hablaba; comer da comía. Ser, ir y ver tienen formas frecuentes irregulares: era, iba, veía. Un hábito pasado puede introducirse con antes o de pequeño.|De pequeña iba al parque cada tarde. Mi barrio era tranquilo y tenía muchas tiendas.|Completa con ir: De pequeña ___ al parque cada tarde (yo).|iba|De pequeña yo ibas al parque cada tarde.|De pequeña yo iba al parque cada tarde.
Planes y futuro próximo|«Ir a + infinitivo» expresa un plan o una previsión. El verbo ir concuerda con el sujeto y el segundo verbo permanece en infinitivo. El presente también puede expresar planes con un marcador futuro. No debemos conjugar los dos verbos de la perífrasis.|Mañana voy a estudiar. El sábado cenamos con unos amigos.|Completa: Mañana voy ___ estudiar.|a|Voy a estudio mañana.|Voy a estudiar mañana.
Comparar personas y cosas|Más o menos + adjetivo + que expresa desigualdad; tan + adjetivo + como, igualdad. Mayor, menor, mejor y peor tienen usos comparativos propios. No confundimos comparar edad con comparar tamaño. El adjetivo mantiene la concordancia con el nombre.|Esta casa es más pequeña que aquella. Mi hermana es mayor que yo.|Completa: Esta casa es más pequeña ___ aquella.|que|Esta casa es más pequeña como aquella.|Esta casa es más pequeña que aquella.
Pronombres de objeto directo|Lo, la, los y las pueden sustituir objetos directos conocidos. Concuerdan en género y número con el referente. Se sitúan delante de un verbo conjugado; con infinitivo pueden ir unidos. La pregunta qué compra o qué ve ayuda a reconocer el objeto.|—¿Compras el pan? —Sí, lo compro. —¿Lees las cartas? —Sí, las leo.|Completa: Las cartas, ___ leo por la tarde.|las|Las cartas, lo leo por la tarde.|Las cartas, las leo por la tarde.
Acciones en curso y rutinas personales|«Estar + gerundio» presenta una acción en desarrollo. El gerundio regular termina en -ando o -iendo. Los verbos pronominales incluyen me, te, se: me levanto. No usamos automáticamente el progresivo para cualquier hábito; «leo cada noche» describe una rutina.|Ahora estoy leyendo. Normalmente me levanto a las siete.|Completa con leer: Ahora estoy ___.|leyendo|Ahora estoy leer.|Ahora estoy leyendo.
Pedir permiso y expresar obligación|Poder + infinitivo expresa posibilidad o permiso; tener que + infinitivo, obligación personal; hay que + infinitivo, necesidad general. El segundo verbo no se conjuga. El contexto y la entonación distinguen una petición amable de una orden.|¿Puedo abrir la ventana? Tengo que estudiar. Hay que llegar a tiempo.|Completa: Tengo ___ estudiar.|que|Tengo estudiar esta tarde.|Tengo que estudiar esta tarde.
Dar instrucciones sencillas|El imperativo afirmativo de tú suele coincidir con la tercera persona del presente: habla, come, escribe. Hay formas frecuentes irregulares: ven, haz, pon. Elegimos el tratamiento adecuado; una instrucción puede suavizarse con por favor. Los pronombres se unen al imperativo afirmativo.|Abre el libro y escribe tu nombre. Ven aquí, por favor.|Completa con abrir: ___ el libro (tú).|Abre|Tú abres el libro, por favor, como orden directa.|Abre el libro, por favor.
Salud y descripción de molestias|«Me duele» se usa con un referente singular y «me duelen» con plural. Tener sirve para síntomas como fiebre. Para describir una molestia concretamos lugar, duración y frecuencia. Estos intercambios son práctica lingüística y no sustituyen una valoración médica.|Me duele la cabeza desde ayer. Me duelen los pies. Tengo fiebre.|Completa: Me ___ los pies.|duelen|Me duele los pies.|Me duelen los pies.
Viajes, reservas y gestiones|Para reservar especificamos fechas, número de personas y preferencias. Quisiera o me gustaría suavizan una petición. Una confirmación repite los datos para evitar errores. Desde y hasta delimitan un periodo; para indica finalidad en contextos como «para dos personas».|Quisiera una habitación para dos personas, desde el lunes hasta el jueves.|Completa: Una habitación ___ dos personas.|para|Una habitación por dos personas, indicando destinatarios.|Una habitación para dos personas.
Mensajes y conectores cotidianos|Y añade información; pero introduce un contraste; porque explica una causa; por eso presenta una consecuencia. Un mensaje breve debe indicar motivo, dato principal y cierre. Los conectores expresan relaciones distintas y no son intercambiables.|No puedo ir porque trabajo. Por eso, te llamaré mañana. Gracias por avisarme.|Completa: No puedo ir ___ trabajo.|porque|No puedo ir por eso trabajo, indicando causa.|No puedo ir porque trabajo.`,
 B1: `Narrar: indefinido e imperfecto|El imperfecto ofrece el fondo, hábitos o acciones en curso; el indefinido presenta sucesos delimitados que avanzan la narración. Ambos pueden aparecer en un mismo relato. La elección depende del punto de vista, no solo de una lista de palabras temporales.|Llovía cuando salí de casa. Mientras esperaba el autobús, encontré a Ana.|Completa con llover: ___ cuando salí de casa.|Llovía|Llovió cuando salía, si el fondo es lluvia continua al salir.|Llovía cuando salí de casa.
Anterioridad en el pasado|El pluscuamperfecto se forma con había, habías, había y un participio. Sitúa un hecho antes de otro punto pasado. No equivale a cualquier pasado lejano: hace falta una relación temporal. Primero identificamos el punto de referencia y después el hecho anterior.|Cuando llegué, Ana ya había salido. Su salida ocurrió antes de mi llegada.|Completa: Cuando llegué, Ana ya ___ salido.|había|Cuando llegué, Ana ya ha salido.|Cuando llegué, Ana ya había salido.
Experiencias y cambios vitales|Llevar + tiempo + gerundio expresa duración de una actividad todavía vigente. Desde introduce el comienzo y desde hace una duración. Dejar de + infinitivo marca el cese; empezar a marca inicio. La elección debe reflejar si la situación continúa.|Llevo dos años estudiando español. Vivo aquí desde 2022. Dejé de fumar.|Completa: Llevo dos años ___ español (estudiar).|estudiando|Llevo dos años estudiar español.|Llevo dos años estudiando español.
Futuro y predicciones|El futuro simple añade terminaciones al infinitivo: hablaré, hablarás, hablará. Algunos verbos cambian la raíz: tendré, podré. Puede expresar previsiones y, según el contexto, suposiciones sobre el presente. Diferenciamos una predicción de un compromiso o de un plan.|Creo que mañana lloverá. No encuentro a Ana; estará en casa.|Completa con llover: Creo que mañana ___.|lloverá|Mañana yo tendrá tiempo.|Mañana yo tendré tiempo.
Condicional y cortesía|El condicional regular añade -ía al infinitivo y comparte raíces irregulares con el futuro: tendría, podría. Sirve para sugerencias, deseos y peticiones atenuadas. El valor depende del contexto; no todas las frases con condicional describen una condición explícita.|¿Podrías ayudarme? Yo hablaría con ella antes de decidir. Me gustaría viajar.|Completa con poder: ¿___ ayudarme? (tú).|Podrías|¿Podría tú ayudarme?|¿Podrías ayudarme?
Deseos y recomendaciones con subjuntivo|Tras querer que o recomendar que usamos subjuntivo cuando hay dos sujetos. Si se mantiene el sujeto, suele usarse infinitivo: quiero viajar. En presente: hablar → hable, comer → coma. No basta identificar una palabra; debemos reconocer la relación entre las acciones.|Quiero que vengas. Quiero viajar. Te recomiendo que descanses.|Completa con descansar: Te recomiendo que ___.|descanses|Quiero que vienes mañana.|Quiero que vengas mañana.
Opiniones, acuerdo y desacuerdo|Creo que suele presentar una afirmación con indicativo; no creo que suele introducir subjuntivo. Para disentir podemos reconocer parte de la opinión y añadir una razón. El tono y el contexto condicionan la cortesía. Una opinión necesita argumentos, no solo una etiqueta.|Creo que funciona. No creo que funcione. Entiendo tu idea, pero cuesta demasiado.|Completa con funcionar: No creo que ___.|funcione|No creo que funciona.|No creo que funcione.
Pronombres de objeto indirecto|Me, te, le, nos, os y les indican destinatario o beneficiario en muchos contextos. Al combinar le o les con lo, la, los o las, usamos se. El referente debe estar claro. En «se lo doy», se identifica al destinatario y lo al objeto entregado.|Doy el libro a Ana → Le doy el libro → Se lo doy.|Completa: El libro a Ana, ___ lo doy.|se|Le lo doy a Ana.|Se lo doy a Ana.
Relativos y descripción precisa|Que introduce información sobre personas o cosas. Donde se relaciona con lugar; cuyo expresa posesión y concuerda con lo poseído. En relativas sencillas, evitamos duplicar el objeto con un pronombre innecesario. El antecedente permite interpretar la información añadida.|La persona que trabaja aquí es Ana. Esta es la casa donde vivo.|Completa: Esta es la casa ___ vivo.|donde|La casa donde vivo en ella es pequeña.|La casa donde vivo es pequeña.
Por y para en situaciones habituales|Para puede indicar finalidad, destinatario o plazo; por puede indicar causa, medio o recorrido. Elegimos según la relación de significado, no por traducción automática. Contrastar dos frases con un mismo nombre ayuda a ver cómo cambia el sentido.|Estudio para aprender. Gracias por ayudarme. Caminamos por el parque.|Completa: Estudio ___ aprender.|para|Estudio por aprender, para expresar finalidad.|Estudio para aprender.
Contar conversaciones y transmitir mensajes|Para transmitir un mensaje adaptamos pronombres, referencias de lugar y tiempo y, cuando corresponde, tiempos verbales. Decir que introduce información; preguntar si una pregunta cerrada. No cambiamos mecánicamente todas las palabras: comprobamos el momento real de la comunicación.|Ana dice: «Estoy cansada» → Ana dice que está cansada. Pregunta: «¿Vienes?» → Pregunta si vienes.|Completa: Ana pregunta ___ vienes.|si|Ana pregunta que vienes, para una pregunta sí/no.|Ana pregunta si vienes.
Escribir y conversar con coherencia|Primero, después y finalmente ordenan una secuencia. Además añade un argumento; sin embargo contrasta; por tanto presenta una conclusión. Un texto coherente mantiene referencias claras y evita repetir información innecesaria. Revisamos que cada conector corresponda a la relación entre ideas.|El curso es útil. Sin embargo, el horario no me conviene. Por tanto, buscaré otro grupo.|Completa: Es útil; ___ embargo, el horario no me conviene.|sin|Es útil; por tanto, el horario no me conviene, como contraste.|Es útil; sin embargo, el horario no me conviene.`,
 B2: `Contrastar indicativo y subjuntivo|En «busco un libro que explica esto» presentamos un referente identificado; en «busco un libro que explique esto» describimos uno no identificado. El subjuntivo no significa simplemente irrealidad. Debemos analizar qué información se afirma y qué queda como requisito, valoración o posibilidad.|Necesito una persona que sepa japonés: no identifico aún a esa persona.|Completa con saber: Necesito una persona que ___ japonés, aún no identificada.|sepa|Necesito una persona que sabe japonés, sin referente identificado.|Necesito una persona que sepa japonés.
Hipótesis y condiciones|Una condición probable puede usar si + presente y futuro. Para hipótesis de presente: si + imperfecto de subjuntivo y condicional. Para un pasado no realizado: si + pluscuamperfecto de subjuntivo y condicional compuesto. La secuencia debe corresponder al tiempo de la hipótesis.|Si tuviera tiempo, viajaría. Si hubiera tenido tiempo, habría viajado.|Completa con tener: Si ___ tiempo, viajaría.|tuviera|Si tendría tiempo, viajaría.|Si tuviera tiempo, viajaría.
Concesión y contraste|Aunque introduce una dificultad que no impide el resultado. El indicativo puede presentar información afirmada; el subjuntivo puede tratarla como hipótesis o como información que no altera la decisión. Sin embargo conecta enunciados, mientras que aunque introduce una subordinada.|Aunque llueve, salimos. Aunque llueva mañana, saldremos: la decisión se mantiene.|Completa con llover: Aunque ___ mañana, saldremos, sea cual sea el tiempo.|llueva|Aunque llover mañana, saldremos.|Aunque llueva mañana, saldremos.
Expresar causas, fines y consecuencias|Porque introduce causa y para que finalidad con dos sujetos. De modo que puede introducir consecuencia; su interpretación depende del contexto. Debemos distinguir lo que motiva una acción de lo que se pretende conseguir. Con el mismo sujeto, para suele acompañar un infinitivo.|Te llamo para que sepas la noticia. Salí pronto porque tenía una cita.|Completa con saber: Te llamo para que ___ la noticia.|sepas|Te llamo para que sabes la noticia.|Te llamo para que sepas la noticia.
Estilo indirecto en pasado|Con un verbo de comunicación pasado, ajustamos el mensaje al nuevo punto de referencia. El presente puede pasar a imperfecto y el futuro a condicional. La adaptación no es obligatoria si la información sigue vigente y el contexto lo permite. También revisamos quién dijo yo y cuándo era mañana.|Ana dijo: «Vendré mañana» → Ana dijo que vendría al día siguiente.|Completa con venir: Ana dijo que ___ al día siguiente.|vendría|Ana dijo que vendré mañana, hablando desde otro día y otra persona.|Ana dijo que vendría al día siguiente.
Pasiva y construcciones con se|La pasiva con ser + participio destaca al paciente; el participio concuerda con él. En la pasiva refleja el verbo concuerda con el sujeto: se venden pisos. En la impersonal con se no hay sujeto: se vive bien. Su elección depende del foco y de la estructura.|Las cartas fueron enviadas. Se venden pisos. Se trabaja bien aquí.|Completa con vender: Se ___ pisos.|venden|Se vende pisos, con pisos como sujeto de pasiva refleja.|Se venden pisos.
Perífrasis y aspecto verbal|Seguir + gerundio expresa continuidad; acabar de + infinitivo, pasado reciente en su uso habitual; volver a + infinitivo, repetición. Debemos conservar la forma no personal exigida por cada perífrasis. Su significado modifica cómo vemos el desarrollo de una acción.|Sigue estudiando. Acaba de llegar. Ha vuelto a llamar.|Completa con estudiar: Sigue ___.|estudiando|Sigue estudiar.|Sigue estudiando.
Argumentación y textos de opinión|Un argumento vincula una tesis con razones y ejemplos. Conceder un punto no obliga a abandonar la tesis. Aun así, en cambio y por consiguiente expresan relaciones diferentes. Una conclusión debe derivarse de lo argumentado, sin introducir pruebas nuevas no explicadas.|El transporte público reduce tráfico. Aun así, necesita más frecuencia para resultar competitivo.|Completa: Tiene ventajas. Aun ___, necesita mejoras.|así|Tiene ventajas; por consiguiente, necesita mejoras, si se pretende contraste.|Tiene ventajas; aun así, necesita mejoras.
Registro formal y comunicación profesional|El registro depende del destinatario, propósito y canal. En una solicitud formal especificamos motivo, petición y datos necesarios. «Le agradecería que…» atenúa una petición y suele acompañarse de imperfecto de subjuntivo. La formalidad no exige frases innecesariamente largas.|Le agradecería que me enviara la información. Quedo a su disposición.|Completa con enviar: Le agradecería que me ___ la información.|enviara|Le agradecería que me enviar la información.|Le agradecería que me enviara la información.
Colocaciones y precisión léxica|Las colocaciones son combinaciones habituales: tomar una decisión, prestar atención, cometer un error. Las palabras cercanas en significado no siempre se combinan igual. Aprender una palabra con un contexto y sus combinaciones evita traducciones literales y mejora la naturalidad.|Tomamos una decisión después de prestar atención a los datos. Cometimos un error.|Completa: Hay que ___ atención a los datos.|prestar|Hay que hacer atención a los datos.|Hay que prestar atención a los datos.
Comprensión de textos y puntos de vista|Distinguir hechos, opiniones e inferencias permite interpretar un texto sin atribuir al autor algo que no afirma. Puede que introduce posibilidad y subjuntivo. Los marcadores de distancia, como según el informe, identifican la fuente. Una inferencia necesita pistas verificables.|Puede que el proyecto funcione, pero el autor no lo garantiza. «Según el informe» atribuye los datos a una fuente.|Completa con funcionar: Puede que el proyecto ___.|funcione|Puede que el proyecto funciona.|Puede que el proyecto funcione.
Negociar, aclarar y reformular|Para confirmar comprensión usamos «si te he entendido bien…». Es decir reformula; más bien corrige o precisa; en otras palabras ofrece otra formulación. Reformular debe conservar el núcleo de significado, no convertir una posibilidad en certeza ni cambiar el alcance de la propuesta.|Si te he entendido bien, propones cambiar la fecha; es decir, aplazar la reunión.|Completa: Es ___, propones aplazar la reunión.|decir|Es decir, cancelar la reunión, si la propuesta original es aplazar.|Es decir, aplazar la reunión.`,
 C1: `Matices de modalidad y compromiso|Un hablante gradúa su compromiso mediante quizá, seguramente, al parecer o sin duda. La elección verbal puede reforzar o atenuar ese compromiso. «Debe de» suele expresar conjetura y «debe» obligación, aunque el uso real admite variación. El contexto evita interpretaciones automáticas.|Debe de estar en casa: deduzco su ubicación. Debe entregar el informe: expreso una obligación.|Completa: Debe ___ estar en casa, marcando explícitamente conjetura.|de|Sin duda quizá llegará, sin una intención expresiva que justifique el choque.|Quizá llegará.
Correlación temporal del subjuntivo|El tiempo de la subordinada expresa su relación con la principal. Con esperaba que, viniera puede indicar simultaneidad o posterioridad; hubiera venido, anterioridad. No basta pasar todo a pasado: primero situamos las acciones y después elegimos las formas.|Esperaba que viniera esa tarde. Dudaba que hubiera llegado antes de la llamada.|Completa con venir: Esperaba que ___ esa tarde.|viniera|Esperaba que venga esa tarde, dentro de un relato pasado cerrado.|Esperaba que viniera esa tarde.
Condiciones mixtas y contrafactuales|Una condición pasada puede tener una consecuencia presente. «Si hubiera estudiado medicina, ahora sería médico» combina pluscuamperfecto de subjuntivo y condicional simple. La mezcla se justifica por los tiempos del significado, no por variación libre. Distinguimos consecuencia actual de resultado pasado.|Si hubiera aceptado el puesto, ahora viviría en Lima. El rechazo pasado explica la situación presente.|Completa con vivir: Si hubiera aceptado, ahora ___ en Lima.|viviría|Si habría aceptado, ahora viviría en Lima.|Si hubiera aceptado, ahora viviría en Lima.
Focalización y orden de la información|El orden puede destacar información nueva o contrastiva. «Fue Ana quien llamó» focaliza a Ana; «lo que necesito es tiempo» focaliza el contenido necesario. La entonación y el contexto ayudan a interpretar el foco. No todo cambio de orden mantiene el mismo efecto comunicativo.|No llamó Luis: fue Ana quien llamó. Lo que necesito es tiempo, no dinero.|Completa: Fue Ana ___ llamó.|quien|Fue Ana que llamó, en esta construcción focalizadora personal.|Fue Ana quien llamó.
Valores de se y estructura verbal|Se puede formar parte de un verbo pronominal, indicar reciprocidad, pasiva o impersonalidad, entre otros valores. «Se arrepintió» no equivale a hacerse algo a sí mismo. Analizamos si hay sujeto, qué complementos aparecen y si la forma con se cambia el significado del verbo.|Ana se arrepintió. Ana y Luis se saludaron. Se publicaron los resultados.|Completa con publicar: Se ___ los resultados.|publicaron|Se publicó los resultados, interpretando resultados como sujeto.|Se publicaron los resultados.
Cohesión, referencia y elipsis|Un texto mantiene su continuidad con pronombres, sinónimos, elipsis y conectores. El referente debe poder recuperarse sin ambigüedad. «Dicho informe» retoma uno ya mencionado; «este» puede ser ambiguo si hay varios candidatos. La cohesión no consiste en reemplazar todas las repeticiones.|El comité publicó un informe. Dicho documento recoge las conclusiones y propone medidas.|Completa: El comité publicó un informe. ___ documento recoge las conclusiones.|Dicho|Ana habló con Marta cuando ella salió, sin indicar a quién refiere ella.|Ana habló con Marta cuando Marta salió.
Marcadores discursivos avanzados|Ahora bien limita o matiza lo anterior; de hecho refuerza con un dato; con todo admite una dificultad sin invalidar la conclusión. Su posición y puntuación ayudan a organizar el discurso. Elegimos el marcador por la relación lógica, evitando acumular varios de función incompatible.|El proyecto es viable. Ahora bien, requiere inversión. Con todo, merece estudiarse.|Completa: El proyecto es viable. Ahora ___, requiere inversión.|bien|El proyecto es viable. De hecho, requiere inversión, si se pretende matizar.|El proyecto es viable. Ahora bien, requiere inversión.
Expresiones idiomáticas en contexto|Una expresión idiomática no se interpreta sumando literalmente sus palabras. «Echar una mano» significa ayudar; «dar en el clavo», acertar. Debemos comprobar registro, región y contexto antes de reutilizarla. Una alternativa literal facilita explicar el significado sin perder el tono.|¿Me echas una mano con las cajas? significa ¿me ayudas con las cajas?|Completa: ¿Me echas una ___ con las cajas?|mano|¿Me echas un brazo?, como expresión habitual para pedir ayuda.|¿Me echas una mano?
Síntesis de fuentes y mediación|Sintetizar exige seleccionar ideas relevantes y relacionarlas sin atribuir al autor afirmaciones propias. «Según» identifica la fuente; «en cambio» diferencia posturas. Mediar consiste en adaptar la información al destinatario manteniendo su sentido y señalando incertidumbres o desacuerdos.|Según el primer informe, la demanda crece; en cambio, el segundo prevé estabilidad.|Completa: ___ el informe, la demanda crece.|Según|Los dos informes coinciden, cuando uno prevé crecimiento y otro estabilidad.|Los informes ofrecen previsiones diferentes.
Ironía, cortesía e implicaturas|El significado comunicativo puede exceder lo literal. «Qué puntual», ante un retraso, puede ser irónico. Para interpretarlo necesitamos contexto, entonación y relación entre interlocutores. No toda afirmación positiva es ironía. Las peticiones indirectas también dependen de lo que ambos saben.|Con la ventana abierta y frío, «¿puedes cerrar?» funciona como petición, no como examen de capacidad.|Completa: Una petición indirecta necesita un ___ compartido para interpretarse.|contexto|Qué puntual siempre expresa un elogio.|Qué puntual puede ser irónico según el contexto.
Escritura académica y profesional|La precisión exige delimitar afirmaciones, organizar párrafos y distinguir resultados de interpretaciones. Cabe señalar introduce una observación; no demuestra por sí mismo una conclusión. Una reserva como «en esta muestra» limita el alcance. Revisamos fuentes, referentes y consistencia terminológica.|En esta muestra, los resultados sugieren una mejora; no permiten generalizar a toda la población.|Completa: Los resultados ___ una mejora, sin demostrarla de forma concluyente.|sugieren|Esta muestra demuestra que toda la población mejora.|Esta muestra sugiere una mejora.
Variación y adecuación sociolingüística|Las variedades del español presentan diferencias legítimas de léxico, pronunciación y gramática. Vos, tú y usted se distribuyen según región y relación social; vosotros y ustedes tampoco tienen el mismo uso en todas partes. Enseñamos adecuación sin presentar una variedad como intrínsecamente superior.|«Tú tienes» y «vos tenés» pertenecen a sistemas de tratamiento distintos. Ambas formas pueden ser adecuadas.|Completa: Con vos, en un uso rioplatense habitual: vos ___ (tener).|tenés|Vos tienes siempre es la única forma correcta en todas las regiones.|Vos tenés es habitual en el español rioplatense.`,
 C2: `Precisión semántica y alcance|Casi todos, todos y no todos tienen alcances distintos. Atenuar una afirmación no equivale a negarla. Al reformular debemos preservar cuantificadores, negación y condiciones. Una frase elegante puede ser inexacta si cambia el grupo al que se refiere o convierte tendencia en universalidad.|No todos aprobaron no significa que nadie aprobara; indica que al menos una persona no aprobó.|Completa: No todos aprobaron no equivale a ___ aprobó.|nadie|No todos aprobaron significa que nadie aprobó.|No todos aprobaron indica que hubo alguna persona que no aprobó.
Reformulación fiel y adaptación|Reformular implica expresar el mismo núcleo con otra estructura y un registro adecuado. «A falta de datos» señala una carencia; no afirma que los datos contradigan la tesis. Conservamos evidencialidad, grado de certeza y excepciones. La mediación puede simplificar términos sin borrar condiciones esenciales.|A falta de datos suficientes, no podemos confirmar la hipótesis → No hay información suficiente para confirmarla.|Completa: No hay información suficiente ___ confirmar la hipótesis.|para|No podemos confirmar la hipótesis significa que es falsa.|No podemos confirmar la hipótesis significa que falta confirmación.
Ambigüedad y desambiguación|Una expresión puede permitir más de una lectura por su estructura, léxico o referentes. La desambiguación explicita la relación relevante. «Vi a Ana con prismáticos» puede referirse al instrumento usado o a lo que llevaba Ana. No escogemos una interpretación sin evidencia contextual.|Vi a Ana usando mis prismáticos aclara el instrumento. Vi a Ana, que llevaba prismáticos, aclara quién los tenía.|Completa: Vi a Ana, ___ llevaba prismáticos.|que|Vi a Ana con prismáticos solo admite una interpretación.|Vi a Ana con prismáticos puede tener dos interpretaciones.
Presuposiciones e información implícita|«Ha dejado de fumar» presenta el cese y presupone que antes fumaba. Las presuposiciones y las implicaturas no funcionan igual: unas se vinculan a determinadas expresiones; otras dependen de inferencias contextuales. Para analizar un mensaje distinguimos contenido afirmado, presupuesto e inferido.|«Ha vuelto a llamar» presupone una llamada anterior. No informa por sí solo de cuántas llamadas hubo.|Completa: Ha vuelto a llamar presupone una llamada ___.|anterior|Ha vuelto a llamar demuestra que llamó exactamente dos veces.|Ha vuelto a llamar presupone que ya había llamado.
Modalidad, evidencialidad y distanciamiento|«Al parecer», «según» y «presuntamente» señalan fuentes o distancia respecto a una afirmación. Suprimirlos puede convertir información atribuida o no confirmada en un hecho presentado como cierto. El registro no justifica borrar la cautela. También distinguimos probabilidad de obligación.|Según la portavoz, el acuerdo está cerrado: se atribuye la afirmación a la portavoz, no se verifica independientemente.|Completa: ___ la portavoz, el acuerdo está cerrado.|Según|El acuerdo está cerrado conserva siempre el mismo compromiso que según la portavoz.|Según la portavoz, el acuerdo está cerrado atribuye la afirmación.
Subordinación y matices temporales|Antes de que sitúa una acción posterior al punto previo expresado por la principal; para que indica finalidad. El modo se relaciona con cómo se presenta la información. En estructuras complejas, trazamos las relaciones temporales y los sujetos antes de decidir tiempos y referentes.|Había salido antes de que llegáramos. Su salida precede a nuestra llegada.|Completa con llegar: Había salido antes de que ___.|llegáramos|Había salido después de que llegáramos mantiene la misma secuencia.|Había salido antes de que llegáramos.
Recursos retóricos y efecto comunicativo|Una antítesis contrapone ideas; una hipérbole exagera; una pregunta retórica no busca necesariamente información. Identificar un recurso exige citarlo y explicar su efecto en ese contexto. No atribuimos intención automáticamente: distinguimos evidencia textual de una interpretación razonada.|«Te lo he dicho mil veces» puede exagerar para expresar insistencia, sin contar literalmente mil repeticiones.|Completa: Te lo he dicho mil veces puede ser una ___.|hipérbole|Te lo he dicho mil veces siempre acredita mil repeticiones exactas.|Te lo he dicho mil veces puede ser una hipérbole.
Colocaciones, polisemia y connotación|Una palabra puede tener varios sentidos y asociaciones valorativas. «Austero» y «mezquino» no son intercambiables aunque ambos puedan relacionarse con gastar poco. El contexto selecciona el sentido y la combinación natural. Sustituimos palabras comprobando significado, registro, connotación y sintaxis.|Un presupuesto austero limita gasto; llamar mezquina a una persona añade una valoración negativa distinta.|Completa: Austero y mezquino no comparten necesariamente la misma ___.|connotación|Austero y mezquino son equivalentes en cualquier descripción.|Austero y mezquino tienen connotaciones distintas.
Humor, ironía y dobles sentidos|El humor puede apoyarse en polisemia, contraste o ruptura de expectativas. La ironía exige reconstruir la distancia entre lo literal y lo comunicado. Al explicarlo señalamos las pistas y admitimos lecturas alternativas cuando el contexto es insuficiente. El doble sentido no equivale siempre a ironía.|Ante una sala desordenada, «menudo orden» puede comunicar una crítica irónica, si la situación y el tono la apoyan.|Completa: Para interpretar la ironía necesitamos pistas del ___.|contexto|Menudo orden siempre elogia la organización.|Menudo orden puede criticar el desorden irónicamente.
Edición de textos complejos|Editar exige jerarquizar cambios: primero contenido y estructura, después cohesión y precisión, finalmente puntuación y estilo. Una corrección no debe modificar sin aviso el alcance de una afirmación. Comprobamos que cada pronombre tenga referente y cada conector exprese la relación adecuada.|«Los datos son escasos; por tanto, la conclusión es provisional» establece una consecuencia coherente.|Completa: Los datos son escasos; por ___, la conclusión es provisional.|tanto|Los datos son escasos; sin embargo, la conclusión es provisional, si se pretende consecuencia.|Los datos son escasos; por tanto, la conclusión es provisional.
Mediación intercultural y registros|Adaptar un mensaje entre contextos culturales requiere explicar referencias, ajustar cortesía y evitar estereotipos. El tratamiento formal no funciona idénticamente en todas las comunidades. Conservamos contenido y propósito, explicitando lo necesario para el destinatario sin atribuir rasgos a todo un grupo.|Para un destinatario que desconoce «puente», podemos explicar: varios días libres junto a un festivo.|Completa: En este contexto, puente designa varios días ___ junto a un festivo.|libres|Todo puente es una construcción sobre un río, incluso en un calendario laboral.|Puente también puede designar días libres junto a un festivo.
Debate, síntesis y posición matizada|Una intervención sólida distingue tesis, razones, objeciones y límites. «No obstante» concede un contraste; «en la medida en que» delimita una relación. Resumir una postura contraria con fidelidad permite responder a su argumento real. La conclusión debe conservar reservas y condiciones.|La propuesta es útil en la medida en que reduce trámites; no obstante, exige garantías para evitar exclusiones.|Completa: La propuesta es útil en la ___ en que reduce trámites.|medida|La propuesta es útil sin condiciones resume fielmente una utilidad condicionada.|La propuesta es útil en la medida en que reduce trámites.`
 };
 const readingChecks = {
  A1:[
   ['¿Cómo se llama la persona que inicia el diálogo?','Ana. Lo indica con «me llamo Ana».'],
   ['¿Qué diferencia hay entre año y ano?','La ñ y la n representan sonidos distintos y cambian la palabra y su significado.'],
   ['¿Qué edad tiene la persona del ejemplo?','Veintidós años. Dice «tengo», no «soy», para expresar la edad.'],
   ['¿Cómo cambia ciudad al hablar de dos?','Pasa a ciudades: añade -es porque termina en consonante.'],
   ['¿Dónde está la farmacia y qué sabemos de ella?','Está junto al banco y es pequeña. Hay presenta su existencia.'],
   ['¿Cuándo trabaja Ana?','Por la tarde. La forma trabaja concuerda con Ana.'],
   ['¿Dónde está la estación y a qué hora abre?','En la plaza; abre a las ocho. Dónde pregunta por lugar y cuándo por momento.'],
   ['¿Cómo es la hermana y cómo es su pelo?','Es alta y tiene el pelo oscuro. Ser describe y tener introduce el rasgo del pelo.'],
   ['¿Qué le gusta a Ana?','El té. Se usa le gusta porque té es singular.'],
   ['Si son las dos y la clase empieza a las tres, ¿falta una hora o tres?','Una hora. Son indica la hora actual y a las el comienzo de la actividad.'],
   ['¿Qué pide la persona y cuánto paga?','Un café; paga dos euros. La petición incluye por favor.'],
   ['¿Adónde va la persona y dónde está la estación?','Va al mercado; la estación está cerca del parque. Al y del son contracciones.']
  ],
  A2:[
   ['¿Cuántas veces ha comido con su hermana esta semana?','Dos veces. He comido se sitúa en esta semana, un marco considerado vigente.'],
   ['¿Qué hizo la persona después de ir al centro?','Compró pan y volvió a casa. Los verbos presentan una secuencia terminada.'],
   ['¿Ir al parque era un hábito o una visita única?','Un hábito de la infancia: iba al parque cada tarde.'],
   ['¿Qué hará mañana y qué plan tiene para el sábado?','Va a estudiar mañana y cenará con unos amigos el sábado.'],
   ['¿Se compara el tamaño de las casas o el de las personas?','El tamaño de las casas; mayor en la segunda frase compara la edad de la hermana.'],
   ['¿Qué sustituye las en las leo?','Las cartas. El pronombre concuerda con ese referente femenino plural.'],
   ['¿Qué acción ocurre ahora y cuál es una rutina?','Leer ocurre ahora; levantarse a las siete es una rutina.'],
   ['¿Cuál de las tres frases pide permiso?','¿Puedo abrir la ventana? Las otras expresan obligaciones o necesidad.'],
   ['¿Qué dos acciones se le piden al interlocutor con el libro?','Abrir el libro y escribir su nombre. Son instrucciones de tú.'],
   ['¿Desde cuándo le duele la cabeza y qué otras molestias menciona?','Desde ayer; también le duelen los pies y tiene fiebre.'],
   ['¿Para cuántas personas y para qué periodo se solicita la habitación?','Para dos personas, desde el lunes hasta el jueves.'],
   ['¿Por qué no puede ir y qué hará mañana?','Porque trabaja; llamará mañana. Por eso introduce la consecuencia.']
  ],
  B1:[
   ['¿La lluvia empezó después de salir o sirve de fondo a la salida?','Sirve de fondo: llovía expresa una situación en curso cuando ocurrió salí.'],
   ['¿Qué ocurrió primero: la salida de Ana o la llegada de quien habla?','La salida de Ana. Había salido expresa anterioridad respecto a llegué.'],
   ['¿Sigue estudiando español? ¿Qué dato lo indica?','Sí, llevo dos años estudiando presenta una actividad vigente y su duración.'],
   ['¿Estará en casa describe un dato comprobado o una suposición?','Una suposición sobre el presente; la persona no encuentra a Ana.'],
   ['¿Podrías ayudarme? se presenta como orden o petición atenuada?','Como petición atenuada mediante el condicional.'],
   ['¿Quién viaja en quiero viajar? ¿Y quién viene en quiero que vengas?','Viaja el sujeto de quiero; viene el interlocutor, un sujeto distinto.'],
   ['¿Funciona se afirma igualmente en creo que funciona y no creo que funcione?','No. La primera presenta una creencia afirmativa; la segunda no afirma el funcionamiento.'],
   ['¿Qué representan se y lo en se lo doy?','Se representa a Ana, destinataria; lo al libro, objeto directo.'],
   ['¿Qué información añade donde vivo sobre la casa?','La identifica como el lugar de residencia de quien habla.'],
   ['¿Qué finalidad y qué causa aparecen en los ejemplos?','Aprender es finalidad del estudio; haber ayudado es motivo del agradecimiento.'],
   ['¿Qué cambia al pasar estoy cansada a Ana dice que está cansada?','El referente pasa de la hablante original a Ana; el presente se conserva en este contexto.'],
   ['¿Por qué se buscará otro grupo aunque el curso sea útil?','Porque su horario no conviene. Sin embargo marca contraste y por tanto, consecuencia.']
  ],
  B2:[
   ['¿La persona que sabe japonés ya está identificada?','No. Sepa formula un requisito para una persona aún no identificada.'],
   ['¿Las dos hipótesis se refieren al mismo momento?','No. Tuviera plantea una hipótesis de presente; hubiera tenido sitúa la condición en el pasado.'],
   ['¿La decisión de salir mañana depende de que llueva?','No: aunque llueva afirma que se saldrá incluso si se da esa dificultad.'],
   ['¿Saber la noticia es la causa previa o la finalidad de la llamada?','La finalidad. Para que introduce el resultado que se pretende conseguir.'],
   ['¿Por qué mañana se reformula como al día siguiente?','Porque se transmite el mensaje desde otro punto temporal de referencia.'],
   ['¿Qué concuerda en las cartas fueron enviadas?','Fueron y enviadas concuerdan con las cartas, femenino plural.'],
   ['¿Qué diferencia hay entre sigue estudiando y ha vuelto a llamar?','La primera indica continuidad; la segunda, repetición de una llamada.'],
   ['¿La falta de frecuencia elimina la ventaja mencionada del transporte público?','No. Aun así reconoce una limitación sin borrar la reducción de tráfico.'],
   ['¿Qué se pide en le agradecería que me enviara la información?','Que el destinatario envíe la información; la fórmula atenúa la petición.'],
   ['¿Cuáles son las combinaciones habituales del ejemplo?','Tomar una decisión, prestar atención y cometer un error.'],
   ['¿El texto garantiza que el proyecto funcionará?','No. Puede que expresa posibilidad y el propio ejemplo rechaza la garantía.'],
   ['¿Se propone cancelar la reunión o celebrarla en otra fecha?','Celebrarla en otra fecha. Aplazar no equivale a cancelar.']
  ],
  C1:[
   ['¿Qué diferencia de compromiso hay entre los dos usos de debe?','Debe de estar presenta una deducción; debe entregar expresa una obligación.'],
   ['¿Qué relación temporal expresa hubiera llegado antes de la llamada?','Una llegada anterior al punto pasado desde el que se expresa la duda.'],
   ['¿Aceptar el puesto y vivir en Lima se sitúan en el mismo momento?','No: aceptar es una condición pasada no realizada y vivir, su consecuencia hipotética presente.'],
   ['¿Qué dos contrastes establece el ejemplo?','Ana frente a Luis como autora de la llamada; tiempo frente a dinero como necesidad.'],
   ['¿Qué valor tiene se en Ana y Luis se saludaron?','Recíproco: ambos se saludan mutuamente. No es el mismo valor de se publicaron.'],
   ['¿A qué remite dicho documento?','Al informe publicado por el comité. Retoma la referencia y evita una repetición literal.'],
   ['¿Ahora bien elimina la viabilidad del proyecto?','No: introduce una condición o reserva, la necesidad de inversión.'],
   ['¿Se pide una mano literalmente?','No. Echar una mano es una expresión idiomática para pedir ayuda.'],
   ['¿Los dos informes sostienen la misma previsión?','No: uno prevé crecimiento de la demanda; el otro, estabilidad.'],
   ['¿Por qué puedes cerrar se entiende como petición en el ejemplo?','La ventana abierta y el frío hacen relevante cerrarla; el contexto permite inferir la intención.'],
   ['¿Puede generalizarse la mejora a toda la población?','No. El ejemplo limita los resultados a esta muestra y habla de una sugerencia.'],
   ['¿Vos tenés es un error por no coincidir con tú tienes?','No. Es una forma de un sistema de tratamiento legítimo, habitual en el español rioplatense.']
  ],
  C2:[
   ['¿No todos aprobaron permite que algunas personas sí aprobaran?','Sí. Niega la universalidad, no afirma que nadie aprobara.'],
   ['¿No confirmar una hipótesis equivale a refutarla?','No. Puede faltar información suficiente; ausencia de confirmación no demuestra falsedad.'],
   ['¿Cómo se distingue quién tiene los prismáticos en las reformulaciones?','Usando mis prismáticos indica el instrumento del observador; que llevaba prismáticos los atribuye a Ana.'],
   ['¿Puede deducirse el número exacto de llamadas de ha vuelto a llamar?','No. Se presupone una llamada anterior, sin determinar cuántas hubo.'],
   ['¿Qué se pierde al omitir según la portavoz?','La atribución de la afirmación a una fuente; puede aumentar el compromiso del emisor con su veracidad.'],
   ['¿Cuál es la secuencia temporal del ejemplo?','Primero salió la persona; después llegamos. Antes de que fija esa relación.'],
   ['¿Se cuenta una frecuencia exacta con mil veces?','No necesariamente: puede ser una exageración que expresa insistencia.'],
   ['¿Por qué mezquino no sustituye sin más a austero?','Añade una valoración negativa distinta; no conserva necesariamente connotación y significado.'],
   ['¿Qué interpretación permite el desorden de la sala?','Una crítica irónica: menudo orden puede comunicar lo contrario de un elogio literal.'],
   ['¿Qué relación expresa por tanto entre datos y conclusión?','Una consecuencia: la escasez de datos justifica que la conclusión sea provisional.'],
   ['¿Por qué se explica puente al destinatario?','Para aclarar una referencia cultural o léxica: aquí alude a días libres alrededor de un festivo.'],
   ['¿La utilidad de la propuesta se afirma sin límites?','No. Depende de reducir trámites y se reconoce la necesidad de garantías frente a exclusiones.']
  ]
 };
 const persons=['yo','tú','él / ella / usted','nosotros / nosotras','vosotros / vosotras','ellos / ellas / ustedes'];
 const paradigm=(forms)=>({head:['Persona','Forma'],rows:persons.map((person,i)=>[person,forms[i]])});
 const verbTables={
  'A1-6':{head:['Persona','Hablar','Comer','Vivir'],rows:persons.map((person,i)=>[person,['hablo','hablas','habla','hablamos','habláis','hablan'][i],['como','comes','come','comemos','coméis','comen'][i],['vivo','vives','vive','vivimos','vivís','viven'][i]])},
  'A2-1':paradigm(['he hablado','has hablado','ha hablado','hemos hablado','habéis hablado','han hablado']),
  'A2-2':paradigm(['compré','compraste','compró','compramos','comprasteis','compraron']),
  'A2-3':paradigm(['iba','ibas','iba','íbamos','ibais','iban']),
  'B1-4':paradigm(['hablaré','hablarás','hablará','hablaremos','hablaréis','hablarán']),
  'B1-5':paradigm(['podría','podrías','podría','podríamos','podríais','podrían']),
  'B1-6':paradigm(['venga','vengas','venga','vengamos','vengáis','vengan'])
 };
 const gapAlternatives={
  'A1-11':['vale'], 'A2-12':['pues','ya que'],
  'B2-2':['tuviese'], 'B2-9':['enviase'], 'B2-10':['poner'],
  'C1-2':['viniese'], 'C1-6':['Este','Ese'], 'C2-4':['previa']
 };
 const vocabularyGames = {
  'A1-1':['Hola|Saludo informal','Buenos días|Saludo de la mañana','Adiós|Despedida'],
  'A1-2':['h|Letra muda en hola','ñ|Letra distintiva de año','a|Primera vocal del alfabeto'],
  'A1-3':['veintidós|22','treinta|30','cuarenta|40'],
  'A1-8':['hermana|Familiar femenino de la misma generación','madre|Progenitora','abuelo|Padre de un progenitor'],
  'A1-11':['¿Cuánto cuesta?|Preguntar el precio','Un café, por favor|Pedir una bebida','Gracias|Agradecer'],
  'A1-12':['a la derecha|Dirección opuesta a la izquierda','cerca de|A poca distancia de','delante de|En la parte anterior de'],
  'A2-10':['Me duele la cabeza|Molestia en la cabeza','Tengo fiebre|Temperatura corporal elevada','Me duelen los pies|Molestia en ambos pies'],
  'A2-11':['reservar|Solicitar que se guarde una plaza','confirmar|Verificar los datos acordados','cancelar|Dejar sin efecto una reserva'],
  'B2-10':['tomar|Una decisión','prestar|Atención','cometer|Un error'],
  'C1-8':['echar una mano|Ayudar','dar en el clavo|Acertar','meter la pata|Equivocarse'],
  'C2-7':['antítesis|Contraposición de ideas','hipérbole|Exageración expresiva','pregunta retórica|Pregunta que no busca necesariamente respuesta']
 };
 for (const level of spanishLevels) {
  const topics=units[level].split('\n').map((line,index)=>{
   const [title,rule,example,prompt,answer,wrong,correction]=line.split('|');
   if(!correction)throw Error('Unidad de español incompleta: '+level+' '+index);
   const id='espanol-'+level.toLowerCase()+'-'+String(index+1).padStart(2,'0');
   const objective='Usar '+title.toLocaleLowerCase('es')+' en una situación comunicativa y justificar la elección con un ejemplo. '+spanishLearningGuidance[level];
   const explanation=rule+'\n\n**Modelo en contexto**\n'+example;
   const transfer='Crea un intercambio o un texto breve de tu vida cotidiana en el que apliques '+title.toLocaleLowerCase('es')+'. Incluye el contexto y explica una elección lingüística.';
   const error='Forma o interpretación que debemos revisar: «'+wrong+'».\n**Corrección:** '+correction;
   const [readingPrompt,readingAnswer]=readingChecks[level][index];
   const practice=[{prompt,answer},{prompt:'Revisa esta forma o interpretación y explica el cambio: «'+wrong+'»',answer:correction+' La explicación debe apoyarse en esta regla: '+rule},{prompt:'Lee este modelo: «'+example+'»\n'+readingPrompt,answer:readingAnswer}];
   const questions=[
    {type:'gaps',prompt,answer,options:[],explanation:rule,alternatives:gapAlternatives[level+'-'+(index+1)]||[]},
    {type:'quiz',prompt:'Elige la forma o interpretación adecuada al contexto de esta unidad.',answer:correction,options:[correction,wrong],explanation:rule},
    {type:'error',prompt:'Corrige o precisa: '+wrong,answer:correction,options:[],explanation:rule},
    {type:'reading',text:example,prompt:readingPrompt,answer:readingAnswer,options:[],rubric:'Revisar que identifica el sentido y lo justifica citando una expresión del modelo.'},
    {type:'flashcard',prompt:title+' · Explica la regla y aporta un ejemplo.',answer:rule+'\n'+example,options:[]},
    {type:'short',prompt:transfer,answer:'Respuesta abierta. Modelo lingüístico: '+example,options:[],rubric:'Valorar adecuación al contexto, significado, estructura y ortografía; admitir otras respuestas válidas.'}
   ].map((question,i)=>({id:id+'-q'+(i+1),text:'',...question}));
   const vocabulary=vocabularyGames[level+'-'+(index+1)];
   if(vocabulary)questions[1]={id:id+'-q2',type:'memory',prompt:'Encuentra las parejas de expresión y significado.',answer:'Completado',text:'',options:vocabulary};
   return {id,title,...(verbTables[level+'-'+(index+1)]?{languageTable:verbTables[level+'-'+(index+1)]}:{}),languageContrast:[wrong,correction],explanation:rule.split(/(?<=[.!?])\s/).slice(0,2).join(' '),example,question:prompt,answer,didactic:{
    objective,explanation,deepDive:rule+'\n\n**Contraste para comprobar el significado**\n'+error,
    concepts:rule.split(/(?<=[.!?])\s/).filter(Boolean),recognition:'Observa la intención del hablante y la relación entre las palabras. En esta unidad, la decisión se apoya en: '+rule.split(/(?<=[.!?])\s/)[0],
    steps:['Lee el modelo y señala qué situación comunica: '+example,'Aplica la regla a una frase propia: '+rule.split(/(?<=[.!?])\s/)[0],'Comprueba el significado comparando con este contraste: '+correction],
    examples:[example,'**Contraste comentado**\n'+error],commonErrors:[error],practice,solutions:practice.map(q=>q.answer),activities:['gaps','quiz','reading','error','short'],transfer,
    preparedMaterial:{title:title+' · Español '+level,summary:'Práctica de forma, significado y uso en contexto, con modelos y revisión del profesor.',duration:20,questions}
   }};
  });
  if(topics.length!==12)throw Error('Cada nivel de español necesita 12 unidades.');
  window.PROFESOR_TEMARIO[level]={...(window.PROFESOR_TEMARIO[level]||{}),'Español':topics};
 }
})();

// Only expose a language level for pupils who study Spanish.
document.addEventListener('change',event=>{
 if(event.target.matches('input[name="subjects"]')) {
  const field=document.querySelector('.spanish-level-field');
  if(field)field.hidden=!document.querySelector('input[name="subjects"][value="Español"]:checked');
 }
});
