/* Personal support-teacher workspace: catalogue stays immutable. */
(() => {
 const clone=x=>JSON.parse(JSON.stringify(x));
 const baseTopics=temarioTopics;
 const fields=[['objective','Objetivo'],['explanation','Explicación'],['deepDive','Ampliación'],['concepts','Conceptos clave',true],['recognition','Cuándo aplicarlo'],['steps','Pasos',true],['examples','Ejemplos resueltos',true],['commonErrors','Errores frecuentes',true],['transfer','Aplicación a otro contexto']];
 let busy=false,retry=null,draftTimer=null;
 function queueDraftSave(){clearTimeout(draftTimer);draftTimer=setTimeout(()=>save(),600);}
 function workspace(){return state.supportWorkspace??={messages:[],draft:null,original:null,sourceId:null,course:temarioCourse,subject:temarioSubject,mode:'new'};}
 function decorate(t){const q=t.didactic.practice;return {...t,didactic:{...t.didactic,solutions:q.map(x=>x.answer),activities:['short'],preparedMaterial:{title:t.title,summary:t.explanation,duration:20,questions:q.map((x,i)=>({id:t.id+'-'+i,type:'short',prompt:x.prompt,answer:x.answer,text:'',options:[]}))}}};}
 temarioTopics=function(){const personal=(state.personalTopics||[]).filter(t=>t.course===temarioCourse&&t.subject===temarioSubject);return [...baseTopics().map(t=>personal.find(p=>p.sourceId===t.id)||t),...personal.filter(p=>!p.sourceId)].map(t=>t.personal?decorate(t):t);};
 const baseView=temarioView;
 temarioView=function(){let html=baseView();html=html.replace('<div class="temario-stage">','<div class="support-entry"><button type="button" data-support="open">✦ Crear o mejorar material'+(!isPremium()?' · Premium':'')+'</button></div><div class="temario-stage">');const t=temarioTopic(temarioSelected);if(t?.personal){html=html.replace('<div class="temario-detail-heading">','<div class="support-personal"><span>Mi versión · Tema personal</span><button data-support="edit">Editar tema</button>'+(t.sourceId?'<button data-support="restore">Restaurar original</button>':'')+'</div><div class="temario-detail-heading">');}return html;};
 const baseResource=openTopicResource;
 openTopicResource=function(topic,kind){
  if(!topic.personal)return baseResource(topic,kind);
  const resource=temarioResources.find(r=>r.kind===kind);if(!resource)return;
  if(resource.premium&&!isPremium()){notify('Este recurso requiere Premium.');return;}
  const d=topic.didactic,section=(title,body)=>'<section class="lesson-card"><h3>'+title+'</h3>'+body+'</section>',list=items=>'<ol>'+items.map(x=>'<li>'+temarioRichText(x)+'</li>').join('')+'</ol>';
  let html='<h2>'+esc(topic.title)+'</h2><p>'+esc(topic.course)+' · '+esc(topic.subject)+'</p>';
  if(kind==='scheme')html+=section('Idea central','<p>'+temarioRichText(topic.explanation)+'</p><p>'+temarioRichText(d.deepDive)+'</p>')+section('Conceptos clave',list(d.concepts))+section('Cómo abordarlo','<p>'+temarioRichText(d.recognition)+'</p>'+list(d.steps));
  if(kind==='examples')html+=d.examples.map((x,i)=>section('Ejemplo resuelto '+(i+1),'<p>'+temarioRichText(x)+'</p>')).join('')+section('Procedimiento',list(d.steps))+section('Errores frecuentes',list(d.commonErrors));
  if(kind==='practice')html+=d.practice.map((q,i)=>section('Ejercicio '+(i+1),'<p>'+temarioRichText(q.prompt)+'</p><details><summary>Ver solución</summary>'+temarioRichText(q.answer)+'</details>')).join('')+section('Aplica lo aprendido','<p>'+temarioRichText(d.transfer)+'</p>');
  html+='<div class="temario-lesson-footer"><button data-topic-pdf="'+kind+'" data-id="'+esc(topic.id)+'">Descargar PDF</button>'+button('Cerrar','close')+'</div>';
  modal(resource.title,'<div class="temario-lesson">'+html+'</div>',()=>false);$('dialog').classList.add('temario-dialog');$('dialog').addEventListener('close',()=>$('dialog').classList.remove('temario-dialog'),{once:true});
 };
 const originalRich=temarioRichText;
 temarioRichText=function(value){return originalRich(value).replace(/\*([^*<>\n]+)\*/g,'<em>$1</em>').replace(/~~([^~<>]+)~~/g,'<u>$1</u>').replace(/\[([^\]<>]+)\]\{(blue|green|purple|orange)\}/g,'<span class="support-color-$2">$1</span>');};
 const style=document.createElement('style');style.textContent=`
 .support-entry{display:flex;justify-content:flex-start;margin:0 0 10px}.support-entry button{color:#8a580d;background:#fff8e9;border-color:#e9cb92;font-weight:750}.support-personal{display:flex;align-items:center;flex-wrap:wrap;gap:8px;padding-bottom:12px;color:#5674a0;font-size:12px}
 .support-drawer{position:fixed;inset:94px 12px 12px auto;width:min(420px,calc(100vw - 24px));z-index:80;background:#fff;border:1px solid #d5e5fa;box-shadow:0 15px 70px #17406b33;border-radius:20px;display:flex;flex-direction:column;color:#102753;overflow:hidden}.support-drawer[hidden]{display:none}.support-drawer header{display:flex;justify-content:space-between;align-items:center;padding:18px;border-bottom:1px solid #e4edfa}.support-drawer h2{font-size:20px;margin:0}.support-context{padding:12px 18px;background:#f4f9ff;font-size:13px}.support-modes{display:flex;gap:6px;flex-wrap:wrap;margin-top:10px}.support-modes button{font-size:12px;padding:8px}.support-modes .active{background:#e7f2ff;color:#0065ed}.support-log{flex:1;min-height:0;overflow:auto;padding:16px}.support-message{background:#f2f7fe;border-radius:14px;padding:12px;margin-bottom:10px;line-height:1.5;font-size:14px;white-space:pre-wrap}.support-message.user{background:#e8f3ff;margin-left:25px}.support-message button{display:block;margin-top:10px}.support-compose{padding:14px;border-top:1px solid #e4edfa;flex-shrink:0}.support-compose textarea{width:100%;height:80px;resize:vertical;max-height:160px}.support-compose footer{display:flex;align-items:center;justify-content:space-between;gap:10px;font-size:12px;margin-top:8px}.support-status{color:#a44225;margin-top:7px;line-height:1.4}.support-editor{width:min(1150px,96vw);max-width:96vw;height:90svh;max-height:94svh;padding:0;border:1px solid #cfdef1;border-radius:20px;color:#102753}.support-editor[open]{display:flex;flex-direction:column}.support-editor::backdrop{background:#13325966}.support-editor>header,.support-editor>footer{padding:14px 20px;display:flex;align-items:center;justify-content:space-between;gap:10px;flex-wrap:wrap;flex-shrink:0;background:#fff}.support-editor header h2{margin:0;font-size:22px}.support-editor>footer{border-top:1px solid #dce8f8}.support-editor-body{display:grid;grid-template-columns:minmax(0,1fr) minmax(0,1fr);min-height:0;flex:1;overflow:auto;gap:18px;padding:0 20px 20px}.support-edit-fields,.support-preview{min-width:0}.support-edit-fields label{display:block;margin:14px 0 6px;font-weight:700;font-size:13px}.support-edit-fields textarea{width:100%;min-height:95px;resize:vertical;font-weight:400}.support-edit-fields input{width:100%;font-weight:400}.support-edit-fields small{display:block;color:#607da5}.support-preview{padding:16px;background:#f5faff;border-radius:16px;line-height:1.65;overflow-wrap:anywhere}.support-preview section{background:white;border:1px solid #e0ebf9;padding:14px;border-radius:12px;margin-bottom:12px}.support-preview h3{font-size:16px;color:#0868dc}.support-preview p{white-space:normal}.support-preview .topic-text-heading{display:block}.support-color-blue{color:#0868dc}.support-color-green{color:#008e6c}.support-color-purple{color:#7951be}.support-color-orange{color:#a6660d}

 .support-column-title{position:sticky;top:0;background:#fff;padding:12px 0;margin:0;font-size:18px;z-index:2;display:flex;justify-content:space-between}.support-column-title small{font-size:12px;color:#607da5;font-weight:400}.support-original,.support-edit-fields{min-width:0}.support-edit-section{background:#f7fbff;border:1px solid #dfebf8;border-radius:12px;padding:14px;margin-top:12px}.support-edit-section h3{margin:0 0 10px;font-size:16px;color:#0868dc}.support-rich-edit{padding:12px;border:1px solid #d3e3f8;border-radius:9px;background:#fff;line-height:1.65;font-size:14px;font-weight:400;min-height:65px;white-space:pre-wrap;overflow-wrap:anywhere}.support-rich-edit:focus{outline:2px solid #67a7ff;outline-offset:1px}.support-rich-edit .topic-text-heading{display:block}.support-edit-item{display:flex;align-items:start;gap:6px;margin-bottom:9px}.support-edit-item .support-rich-edit{flex:1;min-width:0}.support-edit-item>button{padding:5px 9px}.support-edit-fields label{margin-top:10px}.support-formula-tools{margin:15px 0}.support-selection-toolbar{position:absolute;z-index:10;display:flex;align-items:center;gap:3px;border:1px solid #d9e0eb;background:#fff;border-radius:13px;padding:5px;box-shadow:0 8px 30px #10275325;max-width:calc(100% - 16px)}.support-selection-toolbar[hidden]{display:none}.support-selection-toolbar button{padding:5px;border:0;background:transparent;min-width:29px;height:32px;font-size:16px}.support-selection-toolbar button:hover{background:#edf5ff}.support-selection-toolbar .format-bold{font-weight:800}.support-selection-toolbar .format-underline{text-decoration:underline}.format-blue{color:#0868dc}.format-green{color:#008e6c}.format-purple{color:#7951be}.format-orange{color:#a6660d}
 @media(min-width:1250px){body.support-open .workspace-content{width:calc(100% - 440px);margin-left:0;margin-right:440px}body.support-open .temario-renewed .temario-stage{grid-template-columns:minmax(0,1fr) minmax(290px,.8fr)}body.support-open .temario-renewed .temario-controls{grid-template-columns:1fr 1fr 1.2fr auto;gap:10px}body.support-open .temario-renewed .temario-topic-meta{display:none}body.support-open .temario-renewed .temario-topic{grid-template-columns:38px minmax(0,1fr) 25px}}
 @media(max-width:700px){.support-drawer{inset:8px;width:auto}.support-editor{height:96svh}.support-editor-body{grid-template-columns:1fr}.support-editor>footer button{flex:1}.support-preview{margin-top:5px}}`;
 document.head.append(style);
 const drawer=document.createElement('aside');drawer.className='support-drawer';drawer.hidden=true;drawer.setAttribute('aria-label','Crear o mejorar material');document.body.append(drawer);
 const editor=document.createElement('dialog');editor.className='support-editor';editor.id='supportEditor';document.body.append(editor);
 function paint(){const w=workspace();drawer.innerHTML=`<header><h2>✦ Crear o mejorar material</h2><button data-support="close" aria-label="Cerrar Crear o mejorar material">×</button></header><div class="support-context"><strong>${esc(w.course)} · ${esc(w.subject)}</strong><div>${esc(w.sourceTitle||'Tema nuevo')}</div><div class="support-modes">${[['new','Crear tema nuevo'],['improve','Mejorar este tema'],['exercises','Añadir ejercicios']].map(([v,l])=>`<button data-support-mode="${v}" class="${w.mode===v?'active':''}" ${busy?'disabled':''}>${l}</button>`).join('')}</div></div><div class="support-log" role="log" aria-live="polite">${w.messages.length?w.messages.map(m=>`<div class="support-message ${m.role==='user'?'user':''}">${esc(m.text)}</div>`).join(''):'<div class="support-message">Pídeme un tema nuevo o una mejora del seleccionado. Prepararé un borrador editable; nada se actualizará sin que lo guardes.</div>'}${w.draft?'<div class="support-message"><strong>Borrador: '+esc(w.draft.title)+'</strong><button data-support="review">Revisar y editar propuesta</button></div>':''}${busy?'<div class="support-message">Preparando el tema estructurado…</div>':''}</div><div class="support-compose"><textarea id="supportQuestion" aria-label="Petición al Crear o mejorar material" placeholder="Explica qué quieres crear o mejorar…" ${busy?'disabled':''}>${esc(w.input||'')}</textarea><footer><span>1 crédito por petición · edición gratis</span><button class="primary" data-support="send" ${busy?'disabled':''}>${busy?'Generando…':'Enviar'}</button></footer><div class="support-status" role="status">${esc(w.error||'')}</div><button data-support="reset" ${busy?'disabled':''}>Nueva conversación</button></div>`;drawer.querySelector('.support-log').scrollTop=drawer.querySelector('.support-log').scrollHeight;}
 function choose(mode){const w=workspace(),t=temarioTopic(temarioSelected);if(mode!=='new'&&!t){notify('Selecciona primero un tema.');return;}if(w.draft&&!confirm('Iniciar otra propuesta conserva los temas guardados, pero sustituye el borrador actual. ¿Continuar?'))return;Object.assign(w,{mode,course:temarioCourse,subject:temarioSubject,sourceId:mode==='new'?null:t.id,sourceTitle:mode==='new'?'':t.title,original:mode==='new'?null:clone(t),draft:null,messages:[],error:'',input:mode==='new'?'':mode==='exercises'?'Añade ejercicios variados con soluciones explicadas.':'Mejora la explicación con ejemplos concretos y pasos claros.'});retry=null;save();paint();}
 function open(){if(!isPremium()){notify('Crear o mejorar material · Premium. Solicita tu acceso gratuito temporal en educamesuite@gmail.com.');return;}const w=workspace();if(!busy&&!w.messages.length&&!w.draft)choose(temarioTopic(temarioSelected)?'improve':'new');drawer.hidden=false;document.body.classList.add('support-open');paint();drawer.querySelector('textarea').focus();}
 async function send(){if(busy)return;const w=workspace(),question=drawer.querySelector('textarea').value.trim();if(!question)return;w.input=question;w.error='';const payload={course:w.course,subject:w.subject,mode:w.mode,question,topic:w.draft||w.original||undefined};const fingerprint=JSON.stringify(payload);retry=w.retry;if(retry?.fingerprint!==fingerprint)retry={fingerprint,id:uid()};w.retry=retry;save();busy=true;paint();try{const data=await api('/api/profesor/support',{...payload,request_id:retry.id});w.draft={...data.topic,course:w.course,subject:w.subject,id:w.sourceId||uid(),personal:true,sourceId:w.original?.sourceId||(w.original&&!w.original.personal?w.original.id:null)};w.messages.push({role:'user',text:question},{role:'assistant',text:'He preparado «'+w.draft.title+'». Revisa los apartados, ejemplos y ejercicios antes de guardar.'});w.messages=w.messages.slice(-12);w.input='';retry=null;w.retry=null;save();}catch(e){w.error=e.message;}finally{busy=false;save();paint();}}
 function preview(t){const d=t.didactic;return '<h2>'+esc(t.title)+'</h2><p>'+temarioRichText(t.explanation)+'</p>'+fields.map(([key,label,list])=>'<section><h3>'+label+'</h3>'+(list?'<ol>'+d[key].map(x=>'<li>'+temarioRichText(x)+'</li>').join('')+'</ol>':'<p>'+temarioRichText(d[key])+'</p>')+'</section>').join('')+'<section><h3>Ejercicios y soluciones</h3>'+d.practice.map((q,i)=>'<p><strong>'+(i+1)+'. '+temarioRichText(q.prompt)+'</strong></p><details><summary>Ver solución</summary>'+temarioRichText(q.answer)+'</details>').join('')+'</section>';}
 const rawFields=new WeakMap();
 function richEditor(value,attrs=''){return '<div class="support-rich-edit" contenteditable="true" role="textbox" aria-multiline="true" spellcheck="true" '+attrs+'>'+temarioRichText(value)+'</div>';}
 function serializeRich(node){
  if(node.nodeType===3)return node.textContent;
  if(node.nodeType!==1)return '';
  if(node.tagName.toUpperCase()==='MATH')return node.getAttribute('aria-label')||node.textContent;
  const content=[...node.childNodes].map(serializeRich).join(''),tag=node.tagName.toUpperCase();
  if(tag==='BR')return '\n';
  if(tag==='STRONG'||tag==='B')return '**'+content+'**';
  if(tag==='EM'||tag==='I')return '*'+content+'*';
  if(tag==='U')return '~~'+content+'~~';
  if(/^H[1-6]$/.test(tag)||node.classList.contains('topic-text-heading'))return '\n## '+content+'\n';
  if(tag==='LI'||node.classList.contains('topic-text-bullet'))return '\n- '+content;
  const color=[...node.classList].find(c=>c.startsWith('support-color-'))?.slice(14)||({'#0868dc':'blue','#008e6c':'green','#7951be':'purple','#a6660d':'orange'})[(node.getAttribute('color')||'').toLowerCase()];
  if(color)return '['+content+']{'+color+'}';
  if(node.classList.contains('topic-equation-stack')||node.classList.contains('topic-system'))return [...node.children].map(serializeRich).join('\n');
  if(tag==='DIV'||tag==='P'||tag==='OL'||tag==='UL')return content+'\n';
  return content;
 }
 function readRich(el){const record=rawFields.get(el);return record&&!record.dirty?record.raw:serializeRich(el).trim();}
 function showEditor(){activeField=null;const w=workspace();if(!w.draft)return;const d=w.draft.didactic;
  editor.innerHTML=`<header><h2>Revisar propuesta</h2><button data-support="editorClose">Cerrar editor</button></header><div class="support-editor-body"><article class="support-original"><h3 class="support-column-title">Original <small>Solo lectura</small></h3><div class="support-preview" aria-label="Tema original">${w.original?preview(w.original):'<section><h3>Tema nuevo</h3><p>No hay un tema original. Puedes editar la propuesta de la derecha antes de guardarla.</p></section>'}</div></article><article class="support-edit-fields"><h3 class="support-column-title">Propuesta <small>Editable</small></h3><label>Título<input data-support-field="title" value="${esc(w.draft.title)}" maxlength="180"></label><label>Resumen</label>${richEditor(w.draft.explanation,'data-support-field="summary" aria-label="Resumen de la propuesta"')}${fields.map(([key,label,list])=>'<section class="support-edit-section"><h3>'+label+'</h3>'+(list?'<div data-support-list="'+key+'">'+d[key].map((v,i)=>'<div class="support-edit-item">'+richEditor(v,'data-support-item="'+key+'" data-item-index="'+i+'" aria-label="'+label+' '+(i+1)+'"')+'<button data-support-remove-item="'+key+'" data-index="'+i+'" aria-label="Eliminar elemento">×</button></div>').join('')+'</div><button data-support-add-item="'+key+'">+ Añadir elemento</button>':richEditor(d[key],'data-support-field="'+key+'" aria-label="'+label+' de la propuesta"'))+'</section>').join('')}<section class="support-edit-section"><h3>Ejercicios y soluciones</h3><div id="supportExercises">${d.practice.map((q,i)=>exercise(q,i)).join('')}</div><button data-support="addExercise">+ Añadir ejercicio</button></section><details class="support-formula-tools"><summary>Insertar fórmula</summary><input id="supportFormula" placeholder="Ej.: x^2 + 3/4 = 2"><div id="supportFormulaPreview" aria-label="Vista previa de fórmula"></div><button data-support="insertFormula">Insertar en el apartado activo</button></details></article></div><footer><span>El original se conserva. Selecciona texto en la propuesta para darle formato.</span><div>${w.sourceId?'<button data-support="saveUpdate">Actualizar mi versión</button>':''}<button class="primary" data-support="saveNew">${w.sourceId?'Guardar como tema nuevo':'Guardar en mi temario'}</button></div></footer><div class="support-selection-toolbar" role="toolbar" aria-label="Formato del texto seleccionado" hidden>${[['bold','Negrita','B'],['italic','Cursiva','𝘐'],['underline','Subrayar','U'],['blue','Azul','●'],['green','Verde','●'],['purple','Violeta','●'],['orange','Ocre','●'],['removeFormat','Quitar formato','T×']].map(([v,l,text])=>'<button type="button" data-support-format="'+v+'" aria-label="'+l+'" title="'+l+'" class="format-'+v+'">'+text+'</button>').join('')}</div>`;
  editor.querySelectorAll('[contenteditable]').forEach(el=>{let value;if(el.dataset.supportItem)value=d[el.dataset.supportItem][Number(el.dataset.itemIndex)];else if(el.dataset.exercisePart)value=d.practice[Number(el.closest('[data-exercise-index]').dataset.exerciseIndex)][el.dataset.exercisePart];else value=el.dataset.supportField==='summary'?w.draft.explanation:d[el.dataset.supportField];rawFields.set(el,{raw:value,dirty:false});});
  if(!editor.open)editor.showModal();
 }
 function exercise(q,i){return `<section data-exercise-index="${i}"><label>Ejercicio ${i+1}</label>${richEditor(q.prompt,'data-exercise-part="prompt" aria-label="Ejercicio '+(i+1)+'"')}<label>Solución</label>${richEditor(q.answer,'data-exercise-part="answer" aria-label="Solución '+(i+1)+'"')}<button data-support-remove="${i}">Eliminar ejercicio</button></section>`;}
 function sync(){const t=workspace().draft;if(!t)return;editor.querySelectorAll('[data-support-field]').forEach(el=>{const k=el.dataset.supportField,value=el.tagName==='INPUT'?el.value:readRich(el);if(k==='title')t.title=value;else if(k==='summary')t.explanation=value;else t.didactic[k]=value;});editor.querySelectorAll('[data-support-list]').forEach(el=>t.didactic[el.dataset.supportList]=[...el.querySelectorAll('[data-support-item]')].map(readRich));t.didactic.practice=[...editor.querySelectorAll('[data-exercise-index]')].map(el=>({prompt:readRich(el.querySelector('[data-exercise-part="prompt"]')),answer:readRich(el.querySelector('[data-exercise-part="answer"]'))}));t.didactic.solutions=t.didactic.practice.map(q=>q.answer);t.example=t.didactic.examples[0];t.practice=t.didactic.practice[0]?.prompt;queueDraftSave();}
 let activeField=null,savedRange=null;
 function hideFormat(){const toolbar=editor.querySelector('.support-selection-toolbar');if(toolbar)toolbar.hidden=true;}
 function updateSelection(){if(!editor.open)return;const selection=getSelection(),toolbar=editor.querySelector('.support-selection-toolbar');if(!toolbar)return;const anchor=selection?.anchorNode,el=(anchor?.nodeType===1?anchor:anchor?.parentElement)?.closest('.support-rich-edit');if(!el||!editor.contains(el)||selection.isCollapsed||!el.contains(selection.focusNode)){hideFormat();return;}activeField=el;savedRange=selection.getRangeAt(0).cloneRange();const rect=savedRange.getBoundingClientRect(),box=editor.getBoundingClientRect();toolbar.hidden=false;const width=toolbar.offsetWidth,height=toolbar.offsetHeight;toolbar.style.left=Math.max(8,Math.min(rect.left-box.left,box.width-width-8))+'px';toolbar.style.top=Math.max(8,Math.min(rect.top-box.top-height-8,box.height-height-8))+'px';}
 document.addEventListener('selectionchange',updateSelection);
 editor.addEventListener('pointerup',()=>setTimeout(updateSelection,0));
 editor.addEventListener('keydown',e=>{if(e.key==='Escape'&&!editor.querySelector('.support-selection-toolbar')?.hidden){hideFormat();e.preventDefault();}});
 editor.addEventListener('mousedown',e=>{if(e.target.closest('[data-support-format]'))e.preventDefault();});
 editor.addEventListener('focusin',e=>{if(e.target.matches('.support-rich-edit'))activeField=e.target;});
 editor.addEventListener('input',e=>{if(e.target.id==='supportFormula'){editor.querySelector('#supportFormulaPreview').innerHTML=temarioRichText(e.target.value);return;}const el=e.target.closest('.support-rich-edit');if(el){rawFields.get(el).dirty=true;}sync();});
 editor.addEventListener('paste',e=>{if(e.target.closest('.support-rich-edit')){e.preventDefault();document.execCommand('insertText',false,e.clipboardData.getData('text/plain'));}});
 editor.addEventListener('scroll',hideFormat,true);
 editor.addEventListener('cancel',()=>{sync();hideFormat();});
 async function store(asNew){sync();const w=workspace(),t=clone(w.draft),d=t.didactic;if(!t.title.trim()||!t.explanation.trim()||fields.some(([k,,list])=>list?!d[k].length||d[k].some(x=>!x.trim()):!d[k].trim())||!d.practice.length||d.practice.some(x=>!x.prompt.trim()||!x.answer.trim())){notify('Completa los apartados y las soluciones antes de guardar.');return;}
 if(asNew){t.id=uid();t.sourceId=null;}else t.id=w.sourceId||t.id;
 t.updatedAt=new Date().toISOString();t.personal=true;state.personalTopics??=[];const index=state.personalTopics.findIndex(x=>x.id===t.id);if(index<0)state.personalTopics.push(t);else state.personalTopics[index]=t;save();await saveQueue;if(saveFailed){notify('No se ha podido guardar. Tu borrador sigue disponible para reintentar.');return;}temarioCourse=w.course;temarioSubject=w.subject;temarioSelected=t.id;temarioQuery='';w.draft=null;w.messages=[];save();editor.close();drawer.hidden=true;document.body.classList.remove('support-open');render();notify('Tema guardado en tu temario personal.');}
 document.addEventListener('click',e=>{const format=e.target.closest('[data-support-format]');if(format){e.preventDefault();if(!activeField||!savedRange||!editor.contains(activeField))return;activeField.focus();const selection=getSelection();selection.removeAllRanges();selection.addRange(savedRange);const k=format.dataset.supportFormat,colors={blue:'#0868dc',green:'#008e6c',purple:'#7951be',orange:'#a6660d'};document.execCommand(colors[k]?'foreColor':k,false,colors[k]||null);rawFields.get(activeField).dirty=true;sync();updateSelection();return;}
 const addItem=e.target.closest('[data-support-add-item]'),removeItem=e.target.closest('[data-support-remove-item]');if(addItem||removeItem){sync();const key=(addItem||removeItem).dataset[addItem?'supportAddItem':'supportRemoveItem'];if(addItem)workspace().draft.didactic[key].push('');else workspace().draft.didactic[key].splice(Number(removeItem.dataset.index),1);showEditor();save();return;}
 const remove=e.target.closest('[data-support-remove]');if(remove){workspace().draft.didactic.practice.splice(Number(remove.dataset.supportRemove),1);showEditor();save();return;}
 const mode=e.target.closest('[data-support-mode]');if(mode){choose(mode.dataset.supportMode);return;}
 const action=e.target.closest('[data-support]')?.dataset.support;if(!action)return;e.preventDefault();if(action==='open')open();if(action==='close'){drawer.hidden=true;document.body.classList.remove('support-open');}if(action==='send')send();if(action==='reset')choose(workspace().mode);if(action==='review')showEditor();if(action==='editorClose'){sync();editor.close();}
 if(action==='addExercise'){sync();workspace().draft.didactic.practice.push({prompt:'',answer:''});showEditor();save();}
 if(action==='insertFormula'){const value=editor.querySelector('#supportFormula').value;if(activeField&&value&&editor.contains(activeField)){activeField.focus();const range=document.createRange();range.selectNodeContents(activeField);range.collapse(false);const holder=document.createElement('span');holder.contentEditable='false';holder.innerHTML=temarioRichText(value);range.insertNode(holder);holder.after(document.createTextNode(' '));rawFields.get(activeField).dirty=true;sync();}else notify('Selecciona primero un apartado y escribe la fórmula.');}

 if(action==='saveUpdate')store(false);if(action==='saveNew')store(true);
 if(action==='edit'){if(!isPremium()){notify('Edición disponible en Premium.');return;}const t=temarioTopic(temarioSelected),w=workspace();Object.assign(w,{draft:clone(t),original:clone(t),sourceId:t.id,course:temarioCourse,subject:temarioSubject});showEditor();}
 if(action==='restore'&&confirm('¿Restaurar el tema original? Se eliminará tu versión personalizada.')){state.personalTopics=state.personalTopics.filter(t=>t.id!==temarioSelected);save();render();}
 });
 drawer.addEventListener('input',e=>{if(e.target.id==='supportQuestion'){workspace().input=e.target.value;queueDraftSave();}});
 drawer.addEventListener('keydown',e=>{if(e.key==='Enter'&&(e.ctrlKey||e.metaKey)){e.preventDefault();send();}if(e.key==='Escape'){drawer.hidden=true;document.body.classList.remove('support-open');}});
 window.addEventListener('hashchange',()=>{drawer.hidden=true;document.body.classList.remove('support-open');});
 if(ready)render();
})();
